---
- hosts: timesheet
  remote_user: pedro
  become: yes
  tasks:
  - name: Instalar timesheet
    apt: name=ntp state=present
  - name: Garante que o NTP esta rodando
    service: name=ntp state=started enabled=yes
